const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const origin = 'https://danilostoletovic.com';
const escape = s => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const email = '<a class="button" href="mailto:contact@danilostoletovic.com">Discuss your project ↗</a>';
const pages = [
 {
  route:'/case-studies/smart-vehicle/', type:'case', title:'Smart Vehicle case study — Danilo Stoletović',
  description:'How Danilo Stoletović connects Raspberry Pi vision, Docker services, Mecanum drive controls and a native Android client in Smart Vehicle.',
  eyebrow:'CASE STUDY 01 / EDGE AI & ROBOTICS', heading:'Smart Vehicle. From the camera to the controls.',
  intro:'A Raspberry Pi vehicle brings together computer vision, motor control, networking, and a native Android interface. The engineering challenge is keeping those pieces useful when they are all running at once.',
  meta:['Educational & research platform','Python · Kotlin · Docker','4th place + Special Award'],
  sections:[
   ['brief','The project',`<p>Smart Vehicle, originally <em>Pametno Vozilo</em>, grew from hands-on robotics work at ETŠ Nikola Tesla in Niš. I created the platform to connect what happens in a camera frame with software that can control a physical vehicle.</p><p>The project combines Raspberry Pi 5 edge computing with a Kotlin / Jetpack Compose Android control station. The code is open source under the MIT license. Predrag Šubarević mentors the project, with thanks to former mentor Dejan Batanjac.</p><figure><img class="vehicle-photo" src="/img/projects/smart-vehicle.avif" alt="Smart Vehicle prototype with a blue enclosure and four Mecanum wheels" width="800" height="1067" loading="lazy" decoding="async"><figcaption>The actual build: camera, Raspberry Pi, power supply, and drivetrain on one chassis.</figcaption></figure>`],
   ['constraint','The constraint: vision cannot own the whole system',`<p>The first prototype coupled vision and motor control. When inference became busy, control had to wait. That made separation of responsibilities a practical requirement.</p><p>Camera capture, model inference, video delivery, and motor commands have different jobs. They need to cooperate without making the operator wait for every frame to finish processing.</p><aside class="case-callout">The key decision: keep camera processing, inference, and control separate with multithreaded pipelines and Docker services.</aside>`],
   ['implementation','What I built',`<ol class="system-flow" aria-label="System components"><li>Pi Camera v2 → capture</li><li>Raspberry Pi 5 → YOLO</li><li>Android → view & control</li></ol><h3>On the vehicle</h3><p>A Raspberry Pi 5 with 8GB RAM runs Python services for GPIO peripherals, YOLO object detection, and MJPEG video streaming. Four DC geared motors with Mecanum wheels provide movement in multiple directions, driven through L298N H-bridge motor drivers. An XL4015 converter supplies regulated power.</p><h3>In the operator’s hand</h3><p>The native Android client brings live video, drive commands, and telemetry into one control station. YOLO detection happens on the Pi. Google ML Kit OCR runs in the Android client to extract text from the video.</p><div class="evidence-gallery"><figure class="phone-evidence"><img src="/img/projects/yolo.avif" alt="Android Smart Vehicle client displaying YOLO object detections" width="600" height="1327" loading="lazy" decoding="async"><figcaption>Object detection in the Android live view.</figcaption></figure><figure class="phone-evidence"><img src="/img/projects/ocr.avif" alt="Android client displaying text recognized with Google ML Kit OCR" width="600" height="1327" loading="lazy" decoding="async"><figcaption>Text recognition in the Android client.</figcaption></figure></div><h3>When connectivity changes</h3><p>Smart Network monitors the connection and brings up a local fallback hotspot when external Wi-Fi drops. Model Pipeline provides optimization, quantization, and export workflows for TFLite and ONNX models.</p>`],
   ['outcome','What the project demonstrates',`<p>The platform earned <strong>4th place and a Special Award at the 10th Galaksija Cup</strong>. Its public evidence includes the vehicle, Android interface, hardware diagram, and open-source implementation.</p><figure><img src="/img/projects/award.avif" alt="Certificate recording fourth place and the Special Award at the 10th Galaksija Cup" width="565" height="399" loading="lazy" decoding="async"><figcaption>From the project archive: competition recognition.</figcaption></figure><p>The lesson is about system boundaries: separate the expensive work, make control usable, and plan for a dropped connection. Those same decisions matter in apps and connected services.</p><p>Teleoperation and on-device vision are the foundation. LiDAR and SLAM, accessible programming tools, and clearer replication guides are future directions, not shipped capabilities.</p>`],
   ['sources','Explore the implementation',`<ul><li><a href="https://smartvehicle.dev/">Official Smart Vehicle project website</a></li><li><a href="https://github.com/smartvehiclelab/rpi-server">Python Raspberry Pi server</a></li><li><a href="https://github.com/smartvehiclelab/android-client">Kotlin / Jetpack Compose Android client</a></li><li><a href="https://github.com/smartvehiclelab/smart-network">Smart Network fallback service</a></li><li><a href="https://github.com/smartvehiclelab/model-pipeline">Model Pipeline</a></li></ul><p>Planning an Android app or a connected system? Tell me what it should do and what hardware or services it must work with.</p>${email}`]
  ]
 },
 {
  route:'/case-studies/secretary/',type:'case',title:'AI Secretary integration case study — Danilo Stoletović',
  description:'Building a portfolio AI assistant with a lightweight browser interface, curated knowledge, a Cloudflare Worker and the OpenAI Responses API.',
  eyebrow:'CASE STUDY 02 / AI INTEGRATION',heading:'Secretary. A useful conversation at the edge.',
  intro:'An optional AI assistant helps visitors understand my projects and services. The portfolio still works without JavaScript; the assistant is a separate layer with a focused job.',
  meta:['Personal portfolio integration','TypeScript · Cloudflare Workers','Curated public knowledge'],
  sections:[
   ['brief','The visitor problem',`<p>A visitor may know what they need without knowing which service or technology to ask for. The Secretary gives them a conversational route through my portfolio: what I build, how a project relates to their idea, and how to contact me.</p><p>I built the browser interface and the separate Worker API. The assistant is a guide to public information, not a booking system or a substitute for agreeing on scope directly.</p>`],
   ['interface','A small interface with a clear job',`<p>The launcher opens a dialog only when requested. Visitors can ask about projects, services, and technical experience. The interface keeps conversation history for the browser session and offers a reset action.</p><figure><a href="/img/projects/secretary-interface.jpg"><img src="/img/projects/secretary-interface.jpg" alt="Archived Secretary dialog showing its greeting, question input, reset action, and direct email alternative" width="1280" height="720" loading="lazy" decoding="async"></a><figcaption>An archived interface screenshot. Use Ask Ana to try the current interface and persona.</figcaption></figure><p>The main portfolio remains readable without JavaScript. Assistant failures do not remove the project descriptions or the direct email contact route.</p><p><a href="#" data-secretary>Try the current Ask Ana interface ↗</a>. No signup is required.</p>`],
   ['architecture','Where the integration lives',`<ol class="system-flow" aria-label="Secretary request path"><li>Browser → validated request</li><li>Worker → knowledge + API</li><li>Reply → browser</li></ol><p>The frontend calls a TypeScript Cloudflare Worker. The Worker validates the message and optional conversation history, checks the allowed origin and rate limit, combines the request with curated knowledge, and calls the OpenAI Responses API.</p><p>The API key stays on the server. Zod validates configuration, knowledge, and input. The Worker returns a plain-text reply inside JSON; it does not keep a server-side conversation database. Each request carries the optional history it needs.</p>`],
   ['boundaries','Knowledge and safeguards',`<p>Profile, services, projects, and policies are maintained separately from visitor messages. Questions and client-supplied history are untrusted conversational input; they cannot redefine the approved facts.</p><ul><li>Messages, history, and request body sizes are bounded.</li><li>CORS restricts approved browser origins; rate limits constrain request volume.</li><li>Upstream timeouts and failures return sanitized errors.</li><li>Contact guidance points to email and public professional profiles.</li></ul><p>The assistant is instructed not to invent rates, availability, qualifications, clients, or achievements. Those instructions reduce risk; they do not make model answers infallible. The Secretary cannot send emails, book meetings, or commit me to work.</p>`],
   ['outcome','What this demonstrates',`<p>This project demonstrates an end-to-end AI integration: browser interaction, server-side credentials, maintained knowledge, request validation, and error handling. It is a working feature on the portfolio, not a claim of measured conversion uplift.</p><p>The important boundary is between helpful conversation and real commitments. The assistant can explain fit; scope, timing, and pricing are agreed directly.</p><p>For another business, the same approach starts by deciding which questions to answer, which sources are approved, and when to hand the visitor to a person.</p>`],
   ['sources','Read the integration details',`<ul><li><a href="/api.md">Secretary API documentation</a></li><li><a href="/auth.md">Access model and authentication notes</a></li><li><a href="/openapi.json">OpenAPI description</a></li><li><a href="https://github.com/danilostoletovic/portfolio">Portfolio frontend source</a></li></ul><p>Need an assistant, API connection, or practical automation? Send the goal and the systems it needs to connect.</p>${email}`]
  ]
 },
 ...require('./additional-case-studies.cjs')(email),
 {
  route:'/services/mobile-app-development/',type:'service',title:'Freelance Android & Flutter App Developer — Danilo Stoletović',
  description:'Native Android and Flutter app development with Danilo Stoletović: prototypes, API integration, testing, and app store release preparation.',
  eyebrow:'SERVICE / APPLICATION DEVELOPMENT',heading:'An app people can actually use.',
  intro:'Native Android and Flutter development, from a product idea or existing prototype through implementation, integration, and release preparation. Work directly with the person building it.',
  meta:['Kotlin · Jetpack Compose','Flutter · Dart','Remote freelance & project work'],
  sections:[
   ['fit','When this is a good fit',`<p>You have a product idea, a prototype that needs a production implementation, or an app that needs to connect with APIs and backend systems. I help turn the intended user journey into a clear development scope.</p><p>For Android-specific capabilities, Kotlin and Jetpack Compose can provide a native implementation. For a shared application across platforms, Flutter may fit better. The choice depends on device requirements, integrations, budget, and maintenance.</p>`],
   ['delivery','What we can include',`<ul class="service-deliverables"><li>Prototype or MVP development around the essential user journey.</li><li>Native Android interfaces with Kotlin and Jetpack Compose.</li><li>Multiplatform applications with Flutter and Dart.</li><li>API and backend integration, plus practical AI features when they serve the product.</li><li>Testing, packaging, deployment, and release preparation.</li><li>Google Play or Microsoft Store submission preparation where relevant.</li><li>Source handover and a discussion of ongoing maintenance.</li></ul><p>The scope is agreed before development. Store review and approval remain the store’s decision; account access, third-party fees, and supported platforms are discussed for each project.</p>`],
   ['evidence','See the work behind the service',`<h3>Smart Vehicle: native Android connected to hardware</h3><p>A Kotlin / Jetpack Compose control station combines a live camera view, motor commands, telemetry, and OCR with a Raspberry Pi backend. It demonstrates the integration work behind a useful interface.</p><p><a href="/case-studies/smart-vehicle/">Read the Smart Vehicle case study ↗</a></p><h3>Class Timetable: a multiplatform utility</h3><p>An open-source scheduling application for students and educators, built with Flutter, Dart, and Material 3.</p><p><a href="https://github.com/danilostoletovic/class-timetable">Explore Class Timetable source ↗</a></p>`],
   ['process','From idea to agreed scope',`<ol><li>Share the problem, intended users, and target devices.</li><li>We identify the core user journey, integrations, and constraints.</li><li>I explain an implementation approach and we agree on scope.</li><li>I develop, integrate, and prepare the agreed delivery.</li><li>You receive a handover; we discuss future support.</li></ol>`],
   ['questions','Questions before starting',`<details><summary>Do I need a complete specification?</summary><p>No. Start with what people need to accomplish, any reference apps, and the systems the app must connect to. We can work out the technical scope together.</p></details><details><summary>Can you work on an existing app?</summary><p>Potentially. Send the current stack, the problem, and what you want changed. I will need to review the existing project before confirming fit.</p></details><details><summary>What will it cost and how long will it take?</summary><p>That depends on scope, platform requirements, integrations, and current availability. Send the goal and any deadline so we can discuss an estimate directly.</p></details>`],
   ['contact','Tell me what you want to build',`<p>Email the app’s purpose, target platforms, existing materials, and any timing constraints. You do not need to choose a framework before getting in touch.</p>${email}`]
  ]
 },
 {
  route:'/services/business-websites/',type:'service',title:'Freelance Business Website Developer — Danilo Stoletović',
  description:'Fast, responsive business websites and landing pages with Danilo Stoletović: development, SEO foundations, forms, integrations, deployment and handover.',
  eyebrow:'SERVICE / BUSINESS WEBSITES',heading:'A website that does its job.',
  intro:'A business site, portfolio, or landing page should explain what you do and make the next step easy. I build responsive websites and connect the practical systems around them.',
  meta:['Responsive websites & redesigns','Performance & SEO foundations','Direct collaboration'],
  sections:[
   ['fit','Start with what the site needs to do',`<p>You may need a first website, a redesign, or a landing page for a specific offer. We start with the audience and the useful next action: an enquiry, booking, application, or purchase through an agreed external service.</p><p>A small business site often needs clear content, dependable forms, and straightforward maintenance. The implementation should fit that job and the people who will maintain it.</p>`],
   ['delivery','What we can include',`<ul class="service-deliverables"><li>Responsive implementation for phones, tablets, and desktop.</li><li>Clear navigation, readable content, and accessible interaction patterns.</li><li>Performance-conscious images and lightweight page delivery.</li><li>SEO foundations: page titles, descriptions, canonical URLs, internal links, and sitemap.</li><li>Contact forms, booking services, API connections, and automation.</li><li>Domain, DNS, Cloudflare, hosting, and business email configuration.</li><li>Deployment, source handover, and agreed maintenance guidance.</li></ul><p>Content, integrations, hosting costs, and ongoing support are agreed as part of the scope. Search visibility depends on competition, useful content, links, and indexing; a website build does not guarantee a ranking.</p>`],
   ['evidence','A working example: this portfolio',`<p>This site uses semantic HTML and CSS, with an optional AI assistant supplied by a separate Cloudflare Worker. The main content stays readable without JavaScript. Project pages, direct contact routes, and machine-readable resources support different ways of exploring the work.</p><p><a href="https://github.com/danilostoletovic/portfolio">Read the portfolio source ↗</a></p><h3>AI integration when it has a useful job</h3><p>The Secretary helps visitors ask questions about projects and services. It demonstrates how an assistant can sit alongside ordinary website content and direct human contact.</p><p><a href="/case-studies/secretary/">Read the Secretary integration case study ↗</a></p>`],
   ['process','How we get it online',`<ol><li>Define the audience, offer, and main contact or conversion action.</li><li>Review existing content, brand materials, and domain setup.</li><li>Agree on pages, integrations, implementation, and delivery scope.</li><li>Build and check the site across screen sizes.</li><li>Deploy and hand over the agreed setup.</li></ol>`],
   ['questions','Questions before starting',`<details><summary>Can you help with my domain and hosting?</summary><p>Yes. DNS, Cloudflare, hosting, and email setup can be included in the agreed scope. I will first review the current setup and required services.</p></details><details><summary>Can the website have an AI assistant?</summary><p>Yes, where it solves a real visitor problem. We need to define its approved information, expected questions, operating costs, and human handoff.</p></details><details><summary>Will the site rank first on Google?</summary><p>No ranking can be promised. I can implement the technical foundations and useful page structure. Search Console and real enquiry data help evaluate results after launch.</p></details><details><summary>How do you price a website?</summary><p>Pricing depends on content, number of pages, integrations, and support needs. Share your goal, existing site, and timing so we can discuss scope.</p></details>`],
   ['contact','Send me the site and the problem',`<p>If you already have a website, include its URL and what you want improved. For a new one, tell me what your business does, who it serves, and what visitors should do next.</p>${email}`]
  ]
 }
];
const person = {'@type':'Person','@id':origin+'/#person',name:'Danilo Stoletović',url:origin+'/'};
function evidenceMarkup(body, route) {
 return body.replace(/<figure\b[\s\S]*?<\/figure>/g,figure=>{
  if(!figure.includes('<img '))return figure;
  if(/<a href="\/img\//.test(figure))return figure.replace(/<a href="(\/img\/[^\"]+)"/g,`<a class="evidence-link" data-gallery="${route}" href="$1"`);
  return figure.replace(/<img\b[^>]*src="(\/img\/[^\"]+)"[^>]*>/g,(image,src)=>`<a class="evidence-link" data-gallery="${route}" href="${src}">${image}</a>`);
 });
}
for (const p of pages) {
 const url = origin+p.route;
 const graph = [person,{'@type':'WebPage','@id':url+'#page',url,name:p.title,description:p.description,inLanguage:'en',author:{'@id':person['@id']}}, {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:origin+'/'},{'@type':'ListItem',position:2,name:p.type==='case'?'Case studies':'Services',item:origin+(p.type==='case'?'/#case-studies':'/#offers')},{'@type':'ListItem',position:3,name:p.heading,item:url}]}];
 if (p.type==='case') graph.push({'@type':'Article',headline:p.heading,description:p.description,url,mainEntityOfPage:{'@id':url+'#page'},author:{'@id':person['@id']}});
 else graph.push({'@type':'Service',name:p.heading,serviceType:p.route.includes('mobile')?'Android and Flutter app development':'Business website development',url,description:p.description,provider:{'@id':person['@id']}});
 let content = `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escape(p.title)}</title><meta name="description" content="${escape(p.description)}">
<meta name="robots" content="index, follow, max-image-preview:large"><meta name="author" content="Danilo Stoletović">
<link rel="canonical" href="${url}"><meta property="og:type" content="${p.type==='case'?'article':'website'}"><meta property="og:title" content="${escape(p.title)}"><meta property="og:description" content="${escape(p.description)}"><meta property="og:url" content="${url}"><meta property="og:site_name" content="Danilo Stoletović">
<meta property="og:image" content="${origin}/img/${p.route.includes('smart-vehicle')?'projects/smart-vehicle.avif':'profilePicture.avif'}">
<meta name="color-scheme" content="light dark"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/style.css?v=case-studies-1"><link rel="stylesheet" href="/css/content.css?v=1"><link rel="stylesheet" href="/css/secretary.css?v=6"><link rel="stylesheet" href="/css/workshop.css?v=4"><link rel="stylesheet" href="/css/product.css?v=1"><script src="/js/workshop.js?v=4" defer></script><script src="/js/secretary.js?v=7" defer></script>
<script defer src="https://cloud.umami.is/script.js" data-website-id="04cdf09d-b91c-43e4-a3f1-8366d692f8d7"></script>
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph})}</script>
</head><body>
<a class="skip-link" href="#main-content">Skip to content</a>
<header class="site-header wrap"><a class="wordmark" href="/" aria-label="Danilo Stoletović, home">danilo<span class="orange">.</span><span class="wordmark-note">a person who builds things</span></a><nav aria-label="Main navigation"><details class="project-menu"><summary>Case studies</summary><div>${pages.filter(x=>x.type==='case').map(x=>`<a href="${x.route}"${x===p?' aria-current="page"':''}>${escape(x.heading.split('. ')[0])}</a>`).join('')}</div></details><a href="/#offers">Services</a><a href="/#about">About</a><a href="/#press">Field notes</a><a href="mailto:contact@danilostoletovic.com">Say hello ↗</a></nav><label class="theme-control" title="Switch color theme"><input type="checkbox" id="theme-toggle-check" aria-label="Toggle light or dark theme"><span aria-hidden="true">◐</span></label></header>
<main id="main-content" class="wrap reading-page"><div class="page-intro"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/${p.type==='case'?'#case-studies':'#offers'}">${p.type==='case'?'Case studies':'Services'}</a></nav><p class="eyebrow">${p.eyebrow}</p><h1>${escape(p.heading)}</h1><p class="intro">${escape(p.intro)}</p><ul class="page-meta">${p.meta.map(x=>`<li>${escape(x)}</li>`).join('')}</ul></div>
<div class="case-layout"><nav class="page-index" aria-label="On this page"><strong>ON THIS PAGE</strong>${p.sections.map(([id,label])=>`<a href="#${id}">${escape(label)}</a>`).join('')}</nav><div class="page-body">${p.sections.map(([id,label,body])=>`<section id="${id}" aria-labelledby="${id}-heading"><h2 id="${id}-heading">${escape(label)}</h2>${evidenceMarkup(body,p.route)}</section>`).join('\n')}</div></div>
<nav class="related-reading" aria-label="Related reading"><p class="eyebrow">KEEP EXPLORING</p>${pages.filter(x=>x!==p).map(x=>`<a href="${x.route}">${escape(x.title.split(' — ')[0])} ↗</a>`).join('')}</nav></main>
<footer class="site-footer wrap"><span>© 2026 Danilo Stoletović</span><a href="mailto:contact@danilostoletovic.com">contact@danilostoletovic.com</a><a href="/">Back to portfolio ↑</a></footer>
</body></html>\n`;
 content=content.replace(/<a class="wordmark"[\s\S]*?<\/a>/,'<a class="wordmark" href="/" aria-label="Danilo Stoletović, home"><span class="brand-lockup"><img src="/img/logo.svg?v=workshop-2" width="32" height="32" alt=""><span>danilo<span class="orange">.</span></span></span><span class="wordmark-note">a person who builds things</span></a>');
 content=content.replace('<link rel="icon" href="/favicon.ico">','<link rel="icon" type="image/svg+xml" href="/img/favicon/favicon.svg?v=workshop-2"><link rel="alternate icon" href="/favicon.ico?v=workshop-2"><link rel="apple-touch-icon" href="/img/favicon/apple-touch-icon.png?v=workshop-2">');
 const dir=path.join(root,p.route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),content);
}
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${['/',...pages.map(p=>p.route)].map(route=>`  <url><loc>${origin}${route}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Built ${pages.length} public pages and the sitemap.`);
