// Static product page: overview first, depth only after a visitor chooses it.
const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..');
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const projects=[
 {id:'smart-vehicle',name:'SmartVehicle',category:'hardware',label:'EDGE AI / ROBOTICS',summary:'Vision, movement, and networking — working together on a vehicle with actual wheels.',problem:'A busy vision pipeline should not make the operator wait to control the vehicle.',build:'I built a Raspberry Pi 5 vision platform and a native Android control station, connecting live video, motor commands, and telemetry.',decision:'Camera capture, inference and movement have different jobs. Multithreaded pipelines and separate Docker services keep expensive vision work from owning the control path. Smart Network supplies a local fallback hotspot when external Wi-Fi drops.',result:'4th place and a Special Award at the 10th Galaksija Cup. The prototype, Android interface, and source are available to inspect.',tags:['Raspberry Pi 5','Python / YOLO','Kotlin / Compose'],source:'https://smartvehicle.dev/',images:[['smart-vehicle.avif','Actual SmartVehicle prototype with blue enclosure and Mecanum wheels','Actual build / Raspberry Pi 5'],['yolo.avif','Android client showing YOLO object detections','Object detection / Android live view'],['ocr.avif','Android client showing recognized text','Google ML Kit OCR / Android client'],['award.avif','Competition certificate recording fourth place and the Special Award','Recognition / project archive']]},
 {id:'secretary',name:'Ana, AI Secretary',category:'software',label:'AI INTEGRATION / EDGE SOFTWARE',summary:'A useful conversation at the edge. Public portfolio knowledge, clear boundaries, and an opinionated virtual secretary.',problem:'Visitors should be able to ask about a project or explain their idea without knowing which technology or service to search for.',build:'I built the lightweight chat interface and integrated a separate Cloudflare Secretary Worker. Ana helps visitors explore public project, service, and professional information.',decision:'The portfolio stays useful without the assistant. The Worker validates requests, applies rate admission and exact CORS restrictions, and keeps credentials on the server. Conversations use visitor-supplied history, without persisted server tasks.',result:'A working public assistant with a personality, useful portfolio conversations, and a direct path to human contact. No email sending, scheduling, private-data access, or external actions.',tags:['Cloudflare Workers','Public knowledge','Conversational UI'],source:'https://github.com/danilostoletovic/secretary',images:[['secretary-interface.jpg','Archived Secretary interface with its greeting and question input','Actual interface / project archive — use Ask Ana for the current experience']]},
 {id:'class-timetable',name:'Class Timetable',category:'software',label:'FLUTTER / MULTIPLATFORM',summary:'Rotating weeks. Local reminders. A school day that makes sense.',problem:'A changing timetable needs to answer one simple question quickly: what comes next?',build:'A Flutter application with date-aware one-to-eight-week rotations, subject colors, local reminders, and explicit JSON backup and restore.',decision:'Share the scheduling logic, but handle notifications, file saving and release packaging as platform concerns. Backup and restore are explicit transfers, not automatic cloud sync.',result:'An open-source scheduling application with Android, Windows and web release workflows.',tags:['Flutter / Dart','Material 3','Local scheduling'],source:'https://github.com/danilostoletovic/class-timetable',images:[['class-timetable.png','Class Timetable interface with weekdays and rotation controls','Actual application interface / project repository']]},
 {id:'promptui',name:'PromptUI',category:'software',label:'EXPERIMENT / AI INTERFACES',summary:'What if an AI answer came back as an interface you could use?',problem:'Some questions need a table, chart or form rather than another paragraph.',build:'An experimental React and TypeScript workspace with a Bun gateway and streamed OpenUI responses.',decision:'Make generated output inspectable, allow conversational refinement, and surface failed requests. The offline demo is explicitly labeled and never presented as a live model response.',result:'An experimental local workspace demonstrating streamed interfaces and recovery. It is not a production service.',tags:['React / TypeScript','OpenUI','Experimental'],source:'https://github.com/danilostoletovic/PromptUI',images:[['promptui.png','PromptUI offline demo welcome screen','Offline demo / no live model response shown']]},
 {id:'portfolio',name:'This portfolio',category:'software',label:'LIGHTWEIGHT WEB / CLOUDFLARE',summary:'A workshop with the door open. No frontend framework required.',problem:'Show the work quickly, then let visitors choose how much they want to inspect.',build:'Semantic HTML, vanilla CSS and optional JavaScript on Cloudflare Pages, with static case studies and public agent discovery.',decision:'Public content lives in HTML. Browser interactions organize it without a runtime data service. Ana runs in a separate Worker; the portfolio does not duplicate her backend.',result:'A readable, responsive portfolio with progressive project inspection, direct contact routes and static machine-readable resources.',tags:['HTML / CSS','Vanilla JavaScript','Cloudflare Pages'],source:'https://github.com/danilostoletovic/portfolio',images:[]}
];
const services=[
 {id:'website',choice:'I need a website.',label:'WEBSITES',title:'A good site. Without a huge software project.',summary:'A business website, landing page, portfolio, or redesign that is fast, maintainable, and easy to use.',items:['Design & responsive development','Performance & SEO foundations','Hosting, domains & DNS','Handover & maintenance options'],proof:'portfolio',link:'/services/business-websites/'},
 {id:'idea',choice:'I have an app idea.',label:'APPLICATIONS',title:'From rough idea to something usable.',summary:'Native Android and Flutter applications, from the first prototype through integrations and release preparation.',items:['Android & multiplatform apps','APIs & backend integration','Prototype through production','Store release preparation'],proof:'class-timetable',link:'/services/mobile-app-development/'},
 {id:'ai',choice:'I want practical AI.',label:'AI INTEGRATION',title:'Give AI a useful job.',summary:'An assistant or AI feature grounded in your approved information and the workflow people actually need to finish.',items:['Public-facing assistants','Existing-system integration','Clear knowledge & boundaries','Deployment & failure handling'],proof:'secretary',link:'/case-studies/secretary/'},
 {id:'server',choice:'My server is falling over.',label:'SYSTEMS / INFRASTRUCTURE',title:'Let’s make it stay up.',summary:'Investigate the deployment, fix what is failing, and make your infrastructure easier to operate.',items:['Linux & Docker','Cloudflare, DNS & networking','Deployments & migrations','Production troubleshooting'],proof:'smart-vehicle',link:'/case-studies/smart-vehicle/'}
];
function image(p,index=0,group=p.id){
 const item=p.images[index];
 if(!item)return `<div class="source-specimen"><span>&lt;DS&gt;</span><p>HTML · CSS · CLOUDFLARE</p><a href="${p.source}" target="_blank" rel="noopener noreferrer">Inspect the source ↗</a></div>`;
 return `<figure><a class="evidence-link" data-gallery="${group}" href="/img/projects/${item[0]}"><img src="/img/projects/${item[0]}" alt="${esc(item[1])}" loading="lazy" decoding="async"><span class="image-expand" aria-hidden="true">⤢</span></a><figcaption>${esc(item[2])}</figcaption></figure>`;
}
function card(p,index,small=false){return `<article class="work-card ${small?'small-work':''}" data-category="${p.category}" id="${p.id==='smart-vehicle'?'yolo-smart-vehicle':p.id==='secretary'?'ana-project':p.id==='portfolio'?'portfolio-source':p.id}">${image(p,0,`card-${p.id}`)}<div class="work-card-copy"><p class="eyebrow">0${index+1} / ${p.label}</p><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p><a href="/case-studies/${p.id}/" class="inspect-link" data-open-project="${p.id}">Open the case study <span aria-hidden="true">↗</span></a></div></article>`;}
function inspector(p,index){return `<article id="case-${p.id}" class="case-page"${index?' hidden':''}><header class="case-heading"><p class="eyebrow">${p.label}</p><h3>${esc(p.name)}</h3><ul class="case-tags">${p.tags.map(tag=>`<li>${esc(tag)}</li>`).join('')}</ul></header><div class="case-chapters"><button type="button" data-chapter="0">Overview</button><button type="button" data-chapter="1">The build</button><button type="button" data-chapter="2">Evidence</button><button type="button" data-chapter="3">Result</button></div><div class="case-chapter" id="${p.id}-chapter-0"><div class="case-overview"><div><h4>${p.id==='secretary'?'Meet the virtual front desk.':'The short version.'}</h4><p>${esc(p.summary)}</p><details><summary>Why I built it</summary><p>${esc(p.problem)}</p></details>${p.id==='secretary'?'<div class="ana-examples"><span class="eyebrow">TRY A REAL CONVERSATION</span><button type="button" data-secretary data-ana-prompt="What projects has Danilo built?">What has Danilo built? ↗</button><button type="button" data-secretary data-ana-prompt="Could Danilo help with my project?">Could he build something for me? ↗</button></div>':''}</div>${image(p,0,`overview-${p.id}`)}</div></div><div class="case-chapter" id="${p.id}-chapter-1" hidden><h4>What I built</h4><p>${esc(p.build)}</p><details><summary>The important engineering decision</summary><p>${esc(p.decision)}</p></details><a href="/case-studies/${p.id}/">Read the full engineering notes ↗</a></div><div class="case-chapter" id="${p.id}-chapter-2" hidden><h4>Actual work. Open for inspection.</h4><div class="evidence-grid">${p.images.length?p.images.map((_,i)=>image(p,i,`evidence-${p.id}`)).join(''):image(p)}</div></div><div class="case-chapter" id="${p.id}-chapter-3" hidden><h4>What came out of the build</h4><p>${esc(p.result)}</p><a href="${p.source}" target="_blank" rel="noopener noreferrer">${p.id==='smart-vehicle'?'Official project website':'Read the source'} ↗</a></div><footer class="case-footer"><a href="/case-studies/${p.id}/">Full case study ↗</a><a href="#offers" data-inspector-exit>Could I build something for you? ↓</a></footer></article>`;}
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const hero=html.match(/<section class="hero shipping-hero"[\s\S]*?<\/section>/)[0].replace('href="#work"','href="#case-studies"').replace(/<figure class="hero-bench">[\s\S]*?<\/figure>/,'').replace(/<h1 id="hero-name">[\s\S]*?<\/h1>/,'<h1 id="hero-name">Your idea deserves<br class="hero-line-break"> to see the <span class="underlined">light.</span></h1>');
const testimonials=JSON.parse(fs.readFileSync(path.join(root,'data/testimonials.json'),'utf8'));
const excerpts=['I came in with a pretty rough idea of what I wanted, and he turned it into an Android app that actually feels polished and ready to use. Communication was quick, changes were handled without any drama,','The finished site looks great on both desktop and mobile and, importantly, is easy for us to actually use.','What I appreciated most was that he did not overcomplicate the solution.'];
const quotes=testimonials.map((t,i)=>{if(!t.approvedForPublication||!t.quote.includes(excerpts[i]))throw new Error('Feedback excerpt must be publication-approved.');return `<figure class="testimonial" id="client-feedback-${i}"${i?' hidden':''}><blockquote><p>“${esc(excerpts[i])}${i===0?'…':''}”</p></blockquote><figcaption><span class="client-initials" aria-hidden="true">${t.name.split(' ').map(n=>n[0]).join('')}</span><span><strong>${esc(t.name)}</strong><br><span class="small">${esc(t.role)} · ${esc(t.country)}</span></span><span class="quote-count">0${i+1} / 03</span></figcaption><details><summary>Read the complete feedback</summary><p>${esc(t.quote)}</p></details></figure>`;}).join('\n');
const press=JSON.parse(fs.readFileSync(path.join(root,'data/press.json'),'utf8'));
let main=`<main id="main-content" class="wrap workshop-home">
${hero}
<div class="section-divider"><span>IDEA → BUILD → OUT IN THE WORLD</span><span>LESS PITCH. MORE PROOF.</span></div>
<section id="work" class="product-section" aria-labelledby="work-heading"><div id="case-studies"><div class="section-heading"><div><p class="eyebrow">01 / SELECTED WORK</p><h2 id="work-heading">Open the hood.</h2></div><p>The problem. The decisions.<br>The evidence behind the result.</p></div><div class="work-filters" hidden aria-label="Filter projects"><button type="button" data-work-filter="all" aria-pressed="true">All work <span aria-hidden="true">✳</span></button><button type="button" data-work-filter="hardware" aria-pressed="false">Hardware &amp; systems</button><button type="button" data-work-filter="software" aria-pressed="false">AI &amp; software</button></div><div class="flagship-cards">${projects.slice(0,2).map((p,i)=>card(p,i)).join('')}</div><details class="more-work"><summary>Also on the workbench <span>Class Timetable · PromptUI · This portfolio</span><b aria-hidden="true">＋</b></summary><div class="other-work">${projects.slice(2).map((p,i)=>card(p,i+2,true)).join('')}</div></details></div></section>
<section id="offers" class="product-section" aria-labelledby="offers-heading"><div class="section-heading"><div><p class="eyebrow">02 / WHAT I CAN SOLVE</p><h2 id="offers-heading">What brings you here?</h2></div><p>Start with your problem.<br>I’ll figure out the technical part.</p></div><div class="service-workbench"><div class="service-select" aria-label="Choose a service">${services.map((s,i)=>`<a href="#offer-${s.id}" id="service-${s.id}" data-service-select><span>0${i+1}</span><strong>${s.choice}</strong><span class="service-sign" aria-hidden="true">${i?'＋':'−'}</span></a>`).join('')}</div><div class="service-panels">${services.map((s,i)=>`<article id="offer-${s.id}" class="service-panel"${i?' hidden':''}><p class="eyebrow">${s.label}</p><h3>${s.title}</h3><p>${s.summary}</p><ul class="service-includes">${s.items.map(item=>`<li>${item}</li>`).join('')}</ul><a class="button" href="mailto:contact@danilostoletovic.com?subject=${encodeURIComponent('Project inquiry: '+s.label)}">Discuss this project <span aria-hidden="true">＋</span></a><a class="related-service" href="/case-studies/${s.proof}/" data-open-project="${s.proof}">See the work behind this ↗</a><details><summary>What can we include?</summary><p>We agree on scope, timing, delivery and ongoing support before development. <a href="${s.link}">Explore the details ↗</a>.</p></details></article>`).join('')}</div></div><div id="how-i-work" class="handover"><ol><li><span>01</span><strong>Tell me the problem</strong><p>A rough idea is enough.</p></li><li><span>02</span><strong>Agree on the scope</strong><p>Clear work, timing, and cost.</p></li><li><span>03</span><strong>Build &amp; inspect</strong><p>Working software to review.</p></li><li><span>04</span><strong>Ship &amp; hand over</strong><p>Deployment and a usable handover.</p></li></ol></div><noscript><p>More services: <a href="/services/mobile-app-development/">App development</a> · <a href="/services/business-websites/">Business websites</a> · <a href="mailto:contact@danilostoletovic.com">Discuss AI or infrastructure</a>.</p></noscript></section>
<section id="testimonials" class="product-section feedback-section" aria-labelledby="testimonials-heading"><div><p class="eyebrow">03 / CLIENT FEEDBACK</p><h2 id="testimonials-heading">On the other<br>side of the build.</h2><div class="feedback-select" hidden aria-label="Choose client feedback">${['Android app','Website','AI integration'].map((label,i)=>`<button type="button" data-feedback="${i}" aria-pressed="${i===0}">${label}</button>`).join('')}</div></div><div class="feedback-stage"><span class="quote-mark" aria-hidden="true">“</span><!-- testimonials:start -->${quotes}<!-- testimonials:end --><p class="feedback-note">Selected excerpts from client feedback. Full quotations are available above.</p><noscript><p>More feedback: <a href="/index.md">Markdown portfolio</a>.</p></noscript></div></section>
<section id="about" class="product-section person-section" aria-labelledby="about-heading"><div class="person-copy"><p class="eyebrow">04 / THE PERSON AT THE KEYBOARD</p><h2 id="about-heading">I build it.<br>I see it through.</h2><p>I’m Danilo, a freelance full-stack developer and systems builder. For 3+ years, I’ve taken software from an idea through architecture, implementation, and release.</p><details><summary>A little more about me</summary><p>I’m a final-year Electrical &amp; Computer Science student at ETŠ Nikola Tesla in Niš, with a 5.00 GPA. Building is how I connect the theory to the real world.</p><p>My work spans Android, Windows, the web and edge systems, including Google Play and Microsoft Store release preparation.</p><a href="https://www.youtube.com/shorts/g7EoOTN5HAM" target="_blank" rel="noopener noreferrer">Watch my introduction ↗</a></details><a href="https://github.com/danilostoletovic" target="_blank" rel="noopener noreferrer">See what I’m building on GitHub ↗</a></div><div class="person-evidence"><figure class="polaroid"><img src="/img/profilePicture-280.avif" alt="Danilo Stoletović" width="280" height="280" loading="lazy" decoding="async"><figcaption>Hey, that’s me.</figcaption></figure><div class="tool-notes"><p class="eyebrow">THE TOOLS HAVE A JOB</p><strong>Applications people can use</strong><p>Kotlin · Flutter · React · Python</p><strong>Systems that run the software</strong><p>Linux · Docker · Cloudflare · APIs</p></div></div></section>
<section id="press" class="product-section" aria-labelledby="press-heading"><div class="section-heading"><div><p class="eyebrow">05 / NEWS &amp; RECOGNITION</p><h2 id="press-heading">Past the GitHub tab.</h2></div><p>Sometimes the things I build<br>end up in the news.</p></div><div class="press-filters" hidden aria-label="Filter coverage"><button type="button" data-press="all" aria-pressed="true">All sources</button><button type="button" data-press="PRESS" aria-pressed="false">Press</button><button type="button" data-press="recognition" aria-pressed="false">Recognition</button></div><ul class="press-archive">${press.map(item=>`<li data-press-category="${item.category}"><a class="press-entry" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer"><div class="press-source"><span>${item.category==='PRESS'?'PRESS':'RECOGNITION'} / ${item.year}</span><strong>${esc(item.source)}</strong></div><div><h3>${esc(item.headline)}</h3><p>${esc(item.description)}</p></div><span aria-hidden="true">↗</span><span class="sr-only">Opens in a new tab</span></a></li>`).join('')}</ul><p class="press-note">Media coverage and official results. Each entry links to its source; coverage does not imply endorsement.</p></section>
<section id="contact" class="product-section inbox-section" aria-labelledby="contact-heading"><div><p class="eyebrow">06 / AN OPEN INBOX</p><h2 id="contact-heading">Got an idea?<br>Let’s make it work.</h2><p>Send me what you know. It doesn’t need to be a technical specification.<br>We’ll talk about scope, timing, and what makes sense.</p><div class="email-row"><a href="mailto:contact@danilostoletovic.com">contact@danilostoletovic.com</a><button type="button" class="copy-email" aria-label="Copy contact email" hidden>⧉</button></div><p class="contact-note">You’ll work directly with me. <a href="tel:+381677732060">+381677732060</a><span class="copy-status" aria-live="polite"></span></p></div><aside class="ana-desk"><img src="/img/ana-headshot.jpg" alt="Ana, Danilo’s virtual secretary" width="76" height="76" loading="lazy"><p class="eyebrow">THE VIRTUAL FRONT DESK</p><h3>Still figuring it out?</h3><p>Ana knows the projects, the services, and has a personality of her own.</p><a class="meet-ana" href="mailto:contact@danilostoletovic.com" data-secretary>Ask Ana <span aria-hidden="true">▱</span></a></aside></section>
</main>
<dialog id="project-inspector" aria-labelledby="inspector-heading"><header class="inspector-top"><span id="inspector-heading">THE WORKSHOP / CASE-STUDY NOTEBOOK</span><button type="button" data-close-inspector aria-label="Close case study">Close ×</button></header><div class="case-select" aria-label="Choose a case study">${projects.map((p,i)=>`<a id="select-${p.id}" href="/case-studies/${p.id}/" data-case-select><strong>${i===1?'AI Secretary':esc(p.name)}</strong></a>`).join('')}</div><div class="case-pages">${projects.map(inspector).join('')}</div></dialog>`;
// Services follow the introduction. The entire project archive starts closed.
const work=main.match(/<section id="work"[\s\S]*?<\/section>/)[0];
const offers=main.match(/<section id="offers"[\s\S]*?<\/section>/)[0];
const categories=[['all','All work ✳'],['hardware','Hardware & systems'],['ai','AI & software'],['mobile','Mobile & multiplatform'],['web','Websites'],['experiments','Experiments']];
const membership={ 'smart-vehicle':'hardware',secretary:'ai','class-timetable':'mobile',promptui:'ai experiments',portfolio:'web' };
let archive=work.replace(/<div class="section-heading">[\s\S]*?<div class="work-filters"/, '<details class="project-archive"><summary><span><span class="eyebrow">02 / CASE-STUDY ARCHIVE</span><span class="archive-title" id="work-heading" role="heading" aria-level="2">Open the hood.</span><span class="archive-hint">The problem. The decisions. The evidence behind the result.</span></span><span class="archive-action">Explore 5 projects <b aria-hidden="true">＋</b></span></summary><div class="archive-content"><div class="work-filters"');
archive=archive.replace(/<div class="work-filters"[\s\S]*?<\/div>/,`<div class="work-filters" hidden aria-label="Filter projects">${categories.map(([id,label])=>`<button type="button" data-work-filter="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div>`);
archive=archive.replace(/<div class="flagship-cards">[\s\S]*?<\/details><\/div><\/section>/,`<div class="project-grid">${projects.map((p,i)=>card(p,i)).join('')}</div></div></details></div></section>`);
for(const p of projects)archive=archive.replace(`data-category="${p.category}" id="${p.id==='smart-vehicle'?'yolo-smart-vehicle':p.id==='secretary'?'ana-project':p.id==='portfolio'?'portfolio-source':p.id}"`,`data-category="${membership[p.id]}" id="${p.id==='smart-vehicle'?'yolo-smart-vehicle':p.id==='secretary'?'ana-project':p.id==='portfolio'?'portfolio-source':p.id}"`);
main=main.replace(work,'').replace(offers,offers.replace('02 / WHAT I CAN SOLVE','01 / WHAT I CAN SOLVE')+archive).replace(/<div class="section-divider">[\s\S]*?<\/div>/,'');
html=html.replace(/<main id="main-content"[\s\S]*?<\/main>(?:\s*<dialog id="project-inspector"[\s\S]*?<\/dialog>)?/,main);
html=html.replace(/<nav aria-label="Main navigation">[\s\S]*?<\/nav>/,`<nav aria-label="Main navigation"><details class="project-menu"><summary>Case studies</summary><div>${projects.map(p=>`<a href="/case-studies/${p.id}/" data-open-project="${p.id}">${esc(p.name)}</a>`).join('')}</div></details><a href="#offers">Services</a><a href="#about">About</a><a href="#press">Field notes</a><a href="#contact">Say hello</a></nav>`);
html=html.replace(/href="\/css\/workshop\.css\?v=\d+"/g,'href="/css/workshop.css?v=4"').replace(/src="\/js\/workshop\.js(?:\?v=\d+)?"/g,'src="/js/workshop.js?v=4"');
html=html.replace('js/secretary.js?v=6','js/secretary.js?v=7');
if(!html.includes('/css/product.css'))html=html.replace('<link rel="stylesheet" href="/css/workshop.css?v=4">','<link rel="stylesheet" href="/css/workshop.css?v=4">\n  <link rel="stylesheet" href="/css/product.css?v=1">');
html=html.replace(/https:\/\/www\.youtube\.com\/shorts\/Y6Vy7Ho55Bs/g,'https://www.youtube.com/shorts/g7EoOTN5HAM');
html=html.replace(/<a class="wordmark"[\s\S]*?<\/a>/,'<a class="wordmark" href="#" aria-label="Danilo Stoletović, home"><span class="brand-lockup"><img src="/img/logo.svg" width="32" height="32" alt=""><span>danilo<span class="orange">.</span></span></span><span class="wordmark-note">a person who builds things</span></a>');
html=html.replace(/src="img\/logo.avif"/g,'src="/img/logo.svg"');
html=html.replace('alt="DS logo"','alt="Danilo’s workshop mark"');
html=html.replace(/src="\/img\/logo\.svg(?:\?v=[^"]+)?"/g,'src="/img/logo.svg?v=workshop-2"');
html=html.replace(/(href="(?:\/)?(?:img\/favicon\/[^"?]+|favicon\.ico))(?:\?[^"\s]*)?"/g,'$1?v=workshop-2"');
html=html.replace(/<meta name="theme-color" content="[^"]+">/g,'<meta name="theme-color" content="#f6f3e9">');
if(!html.includes('class="footer-profiles"'))html=html.replace('<nav aria-label="Site checks">','<div class="footer-profiles"><a href="https://github.com/danilostoletovic">GitHub</a><a href="https://linkedin.com/in/danilostoletovic">LinkedIn</a><a href="https://www.upwork.com/freelancers/danilostoletovic">Upwork</a><a href="https://pro.fiverr.com/freelancers/stoletovicd">Fiverr Pro</a></div><nav aria-label="Site checks">');
fs.writeFileSync(path.join(root,'index.html'),html);
console.log('Built the product homepage: choose → inspect → evidence.');
